include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(MOSQUITTO_INCLUDE_DIR mosquitto.h)

find_library(MOSQUITTO_LIBRARY_DEBUG
    NAMES mosquitto mosquitto_static
    NAMES_PER_DIR PATH_SUFFIXES lib
    PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug"
    NO_DEFAULT_PATH REQUIRED
)
find_library(MOSQUITTOPP_LIBRARY_DEBUG
    NAMES mosquittopp mosquitto_static
    NAMES_PER_DIR PATH_SUFFIXES lib
    PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug"
    NO_DEFAULT_PATH REQUIRED
)
find_library(MOSQUITTO_LIBRARY_RELEASE
    NAMES mosquitto mosquitto_static
    NAMES_PER_DIR PATH_SUFFIXES lib
    PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
    NO_DEFAULT_PATH REQUIRED
)
find_library(MOSQUITTOPP_LIBRARY_RELEASE
    NAMES mosquittopp mosquitto_static
    NAMES_PER_DIR PATH_SUFFIXES lib
    PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
    NO_DEFAULT_PATH REQUIRED
)

select_library_configurations(MOSQUITTO)
select_library_configurations(MOSQUITTOPP)

mark_as_advanced(
    MOSQUITTO_INCLUDE_DIR
    MOSQUITTO_LIBRARY_DEBUG
    MOSQUITTO_LIBRARY_RELEASE
    MOSQUITTOPP_LIBRARY_DEBUG
    MOSQUITTOPP_LIBRARY_RELEASE)

add_library(mosquitto::mosquitto UNKNOWN IMPORTED)
set_target_properties(mosquitto::mosquitto PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${MOSQUITTO_INCLUDE_DIR}
    IMPORTED_LINK_INTERFACE_LANGUAGES "C")

set_target_properties(mosquitto::mosquitto PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    IMPORTED_LOCATION "${MOSQUITTO_LIBRARIES}")

if(MOSQUITTO_LIBRARY_DEBUG)
    set_property(TARGET mosquitto::mosquitto APPEND PROPERTY
        IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(mosquitto::mosquitto PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
        IMPORTED_LOCATION_DEBUG "${MOSQUITTO_LIBRARY_DEBUG}")
endif()
if(MOSQUITTO_LIBRARY_RELEASE)
    set_property(TARGET mosquitto::mosquitto APPEND PROPERTY
        IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(mosquitto::mosquitto PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
        IMPORTED_LOCATION_DEBUG "${MOSQUITTO_LIBRARY_RELEASE}")
endif()

add_library(mosquitto::mosquittopp UNKNOWN IMPORTED)
set_target_properties(mosquitto::mosquittopp PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${MOSQUITTO_INCLUDE_DIR}
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX")

set_target_properties(mosquitto::mosquittopp PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
    IMPORTED_LOCATION "${MOSQUITTOPP_LIBRARIES}")

if(MOSQUITTOPP_LIBRARY_DEBUG)
    set_property(TARGET mosquitto::mosquittopp APPEND PROPERTY
        IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(mosquitto::mosquittopp PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
        IMPORTED_LOCATION_DEBUG "${MOSQUITTOPP_LIBRARY_DEBUG}")
endif()
if(MOSQUITTOPP_LIBRARY_RELEASE)
    set_property(TARGET mosquitto::mosquittopp APPEND PROPERTY
        IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(mosquitto::mosquittopp PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
        IMPORTED_LOCATION_DEBUG "${MOSQUITTOPP_LIBRARY_RELEASE}")
endif()